version: 0.1.{build}

image: Visual Studio 2015

environment:
  matrix:
    # Python 3.6 - 32-bit
    #- PYTHON: "C:\\Python36"
    # Python 3.5 - 64-bit
    - PYTHON: "C:\\Python35-x64"

#---------------------------------#
#        build                    #
#---------------------------------#

build: off

configuration: Release

install:
  - SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%;C:\MinGW\bin
  - copy c:\MinGW\bin\mingw32-make.exe c:\MinGW\bin\make.exe
  - copy c:\Python35-x64\python.exe c:\Python35-x64\python3.exe
  - python --version
  - make install

after_test:
  - make package
  - '7z a DEXBot-win64.zip %APPVEYOR_BUILD_FOLDER%\dist\DEXBot-gui.exe %APPVEYOR_BUILD_FOLDER%\dist\DEXBot-cli.exe'

# @TODO: Run tests..
test_script:
  - "echo tests..."

artifacts:
  - path: DEXBot-win64.zip
    name: DEXBot-win64.zip

#---------------------------------#
#        deployment               #
#---------------------------------#

shallow_clone: false

clone_depth: 1

deploy:
  - provider: GitHub
    artifact: DEXBot-win64.zip
    draft: false
    prerelease: false
    force_update: true
    auth_token:
      secure: 8uowqY8PJ/HTwN2MGDRWgsMgGR6wCbf8gJSqhJhS8iND/XysNBFk3Lp2ATe7gp8h
    on:
      appveyor_repo_tag: true     # deploy on tag push only
